pollsCBV/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from mysite.views import HomeView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^polls/', include('polls.urls')),
    url(r'^polls-new/', include('polls_new.urls')),
]

pollsCBV/polls/urls.py
from django.conf.urls import url
from polls import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.PollsIndexView.as_view(), name='index'),
    url(r'^(?P<pk>[\d+])/$', views.PollsDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[\d+])/vote/$', views.vote, name='vote'),
    url(r'^(?P<pk>[\d+])/result/$', views.PollsResultView.as_view(), name='result'),
]

pollsCBV/polls_new/urls.py
from django.conf.urls import url
from polls_new import views


app_name = 'polls_new'
urlpatterns = [
    url(r'^$', views.PollsIndexView.as_view(), name='index'),

    # url(r'^(?P<pk>[\d+])/$', views.PollsDetailView.as_view(), name='detail'),
    # url(r'^(?P<pk>[\d+])/vote/$', views.vote, name='vote'),
    # url(r'^(?P<pk>[\d+])/$', views.PollsFormView.as_view(), name='detail'),
    url(r'^(?P<pk>[\d+])/$', views.PollsSOMFV.as_view(), name='detail'),

    url(r'^(?P<pk>[\d+])/result/$', views.PollsResultView.as_view(), name='result'),
]

pollsCBV/polls/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models


@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollsCBV/polls_new/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models


@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollsCBV/polls_new/forms.py
from django import forms

from polls.models import Question


def get_choices():
    # choiceList = [
    #     (1, 'aaa'),
    #     (2, 'bbb'),
    #     (3, 'CCC'),
    # ]

    object = Question.objects.first()
    choiceList = [(i.pk, i.choice_text) for i in object.choice_set.all()]
    return choiceList


'''
class PollsRadioForm(forms.Form):

    # choiceList = [
    #     (1, 'aaa'),
    #     (2, 'bbb'),
    #     (3, 'ccc'),
    # ]

    question = Question.objects.first()
    my_choice_field = forms.ChoiceField(
        # label="What's your name ?",
        label=question.question_text,
        choices=get_choices(),
        widget=forms.RadioSelect,
    )
'''


class QuestionRadioForm(forms.Form):

    # question = Question.objects.first()
    # my_choice_field = forms.ChoiceField(
    #     # label="What's your name ?",
    #     label=question.question_text,
    #     choices=get_choices(),
    #     widget=forms.RadioSelect,
    # )

    def __init__(self, question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['my_choice_field'] = forms.ChoiceField(
            label=question.question_text,
            # choices=get_choices(),
            choices=self.get_choices(question),
            widget=forms.RadioSelect,
        )

    def get_choices(self, question):
        # object = Question.objects.first()
        choiceList = [(i.pk, i.choice_text) for i in question.choice_set.all()]
        return choiceList

pollsCBV/mysite/views.py
from django.views.generic.base import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

pollsCBV/polls/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from polls.models import Question, Choice


class PollsIndexView(ListView):
    # model = Question
    queryset = Question.objects.order_by('-pub_date')[:5]
    template_name = 'polls/index.html'


class PollsDetailView(DetailView):
    model = Question
    template_name = 'polls/detail.html'


class PollsResultView(DetailView):
    model = Question
    template_name = 'polls/result.html'


def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        select = request.POST['choice']
        selected_choice = question.choice_set.get(pk=select)
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return redirect('polls:result', question.id)

pollsCBV/polls_new/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse_lazy
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import FormView
from django.views.generic.list import ListView

from polls.models import Question, Choice
# from polls_new.forms import PollsRadioForm
from polls_new.forms import QuestionRadioForm


class PollsIndexView(ListView):
    # model = Question
    queryset = Question.objects.order_by('-pub_date')[:5]
    template_name = 'polls_new/index.html'


class PollsDetailView(DetailView):
    model = Question
    template_name = 'polls_new/detail.html'


class PollsResultView(DetailView):
    model = Question
    template_name = 'polls_new/result.html'


# def vote(request, pk):
#     question = get_object_or_404(Question, pk=pk)
#     try:
#         select = request.POST['choice']
#         selected_choice = question.choice_set.get(pk=select)
#     except (KeyError, Choice.DoesNotExist):
#         return render(request, 'polls_new/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         return redirect('polls_new:result', question.id)


class PollsFormView(FormView):
    # form_class = PollsRadioForm
    form_class = QuestionRadioForm
    template_name = 'polls_new/detail.html'
    # success_url = reverse_lazy('polls_new:index')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        object = Question.objects.first()
        kwargs.update({'question': object})
        return kwargs

    def form_valid(self, form):
        object = Question.objects.first()
        select = form.cleaned_data['my_choice_field']
        selected_choice = object.choice_set.get(pk=select)

        selected_choice.votes += 1
        selected_choice.save()
        # return redirect('polls_new:result', object.id)
        return super().form_valid(form)

    def get_success_url(self):
        object = Question.objects.first()
        return reverse_lazy('polls_new:result', kwargs={'pk': object.id})


class PollsSOMFV(SingleObjectMixin, FormView):
    model = Question
    form_class = QuestionRadioForm
    template_name = 'polls_new/detail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # object = Question.objects.first()
        kwargs.update({'question': self.object})
        return kwargs

    def form_valid(self, form):
        # object = Question.objects.first()
        select = form.cleaned_data['my_choice_field']
        selected_choice = self.object.choice_set.get(pk=select)

        selected_choice.votes += 1
        selected_choice.save()
        # return redirect('polls_new:result', object.id)
        return super().form_valid(form)

    def get_success_url(self):
        # object = Question.objects.first()
        return reverse_lazy('polls_new:result', kwargs={'pk': self.object.id})

pollsCBV/mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% load staticfiles %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}home.html{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <!-- my css -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    {% block extra-style %}{% endblock %}

</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}">Home</a></li>

            <li><a href="{% url 'polls:index' %}">Polls</a></li>
            <li><a href="{% url 'polls_new:index' %}">PollsNew</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
        </ul>

    </div><!--/.container -->
</nav><!--/.navbar -->

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{% block extra-script %}{% endblock %}

</body>
</html>

pollsCBV/mysite/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}home.html{% endblock %}

{% block extra-style %}

<style type="text/css">

.homewindow {
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    color: yellow;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}

footer.footer-wrapper {
    background: #456;
    color: #eee;
    line-height: 50px;
}
.footer-wrapper a {
    color: #ff9;    /* footer-right text */
}
.footer-wrapper a:hover {
    color: #0ff;
}

</style>
{% endblock extra-style %}

{% block content %}

    <div class="homewindow">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="glyphicon glyphicon-cog"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-md-4">
            <h3>Bookmark</h3>
            <p>You can store your own bookmarks by Bookmark application. It's also possible to update or delete your bookmarks.</p>
        </div>
        <div class="col-md-4">
            <h3>Blog</h3>
            <p>This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc.</p>
        </div>
        <div class="col-md-4">
            <h3>Photo</h3>
            <p>You can upload your own photos through this application. If you delete an album, all photos within it will be deleted.</p>
        </div>
    </div>

{% endblock content %}

{% block footer %}
<footer class="navbar-fixed-bottom footer-wrapper">

    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <p>
                    Copyright &copy; 2017 DjangoBook by shkim
                </p>
            </div>
            <nav class="col-md-7">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="#" rel="tooltip" data-placement="top" data-original-title="준비중입니다">PyCon 2017</a>
                    </li>
                    <li>
                        <a href="#" rel="tooltip" data-placement="top" data-original-title="준비중입니다">Hanbit Media</a>
                    </li>
                    <li>
                        <a href="#" rel="tooltip" data-placement="top" data-original-title="준비중입니다">About Me</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</footer>
{% endblock footer %}

{% block extra-script %}
<script>
$(function () {
    $('[rel=tooltip]').tooltip({
        delay: {show:10, hide:100}
    });
});
</script>
{% endblock extra-script %}

pollsCBV/polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}

    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post"> {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>

{% endblock content %}

pollsCBV/polls/templates/polls/index.html
{% extends "base.html" %}

{% block content %}

    <h2>Polls Question List</h2>

    {% if question_list %}
        <ul>
        {% for question in question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock content %}

pollsCBV/polls/templates/polls/result.html
{% extends "base.html" %}

{% block content %}

    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock content %}

pollsCBV/polls_new/templates/polls_new/detail.html
{% extends "base.html" %}

{% block content %}

    <h3>{{ form.my_choice_field.label_tag }}</h3>

    <form action="" method="post"> {% csrf_token %}

        {% for radio in form.my_choice_field %}
        <div class="col-sm-offset-1">
            {{ radio }}
        </div>
        {% endfor %}

        {# form #}

    <input type="submit" class="btn btn-warning btn-sm" value="Vote" />
    </form>

{% endblock content %}

pollsCBV/polls_new/templates/polls_new/index.html
{% extends "base.html" %}

{% block content %}

    <h2>Polls (New) Question List</h2>

    {% if question_list %}
        <ul>
        {% for question in question_list %}
            <li><a href="{% url 'polls_new:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock content %}

pollsCBV/polls_new/templates/polls_new/result.html
{% extends "base.html" %}

{% block content %}

    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls_new:detail' question.id %}">Vote again?</a>

{% endblock content %}